### ISSUE TITLE
Tutorial is stuck on Step 4 - Does not proceed to step 5

### ISSUE THREAD

**Issue by 1dropaflame** [skills/github-pages#94] opened 2024-01-25 18:33 UTC
### Discussed in https://github.com/orgs/skills/discussions/468

<div type='discussions-op-text'>

<sup>Originally posted by **CodaCodr** January 12, 2024</sup>
Hi

I'm working through the course to create a github blog. It worked fine until the end of step 4. I've waited ~5mins or more, refreshing does nothing.

How do I proceed?
</div>

**Comment by hectorsector** [comment] 2024-02-12 16:23
Hello there! I've taken the course and verified it's working. I tried looking for your repository but I cannot see it, so it may be private or deleted since you opened this issue. Since I cannot reproduce the bug, I'll go ahead and close this issue but please open again if I'm misunderstanding. Thanks.

**Closed by hectorsector** 2024-02-12 16:23 UTC

**Comment by 1dropaflame** [comment] 2024-12-04 21:33
It is not fixed. see https://github.com/orgs/skills/discussions/468

**Comment by msaltenna** [comment] 2025-03-12 20:16
still a problem in 2025 stuck on step #4

**Comment by kalenz86** [comment] 2025-03-12 21:02
y

**Comment by gokidcbk** [comment] 2025-03-13 11:26
almost like 6-7

**Comment by ira-ilchyshyn** [comment] 2025-08-05 13:02
still an issue

**Comment by ira-ilchyshyn** [comment] 2025-08-05 13:02
reproducible bug
Please reopen issue

**Comment by Hoooyo7878** [comment] 2025-08-06 19:45
Asc Like fille isodira shp
